Repository upgrades-migrations/preupgrade-assistant-modules, pull requests merged in 2018-09, with the labels that each got.

#103 system/java-1.8.0-ibm - check for package being present before update
  RHEL6_7/system/java-1.8.0-ibm/check
  RHEL6_7/system/java-1.8.0-ibm/module.ini
  RHEL6_7/system/java-1.8.0-ibm/module_spec
  RHEL6_7/system/java-1.8.0-ibm/remove-java-1.8.0-ibm-pre-upgrade.sh
  RHEL6_7/system/java-1.8.0-ibm/solution.txt
Labels: enhancement, needs_verify, qa_ack, qa_verified

#105 fix used modes for os.chmod in python's scripts
  RHEL6_7/services/tomcat/check
  RHEL6_7/system/java-1.8.0-ibm/check
Labels: bug

#98 networking/samba - RFE
  RHEL6_7/networking/samba/check
  RHEL6_7/networking/samba/postupgrade.d/postupgrade_smb.sh
Labels: enhancement, needs_verify, on_qe, qa_ack, text_reviewed
