Repository upgrades-migrations/preupgrade-assistant-modules, pull requests merged in 2020-07, with the labels that each got.

#124 Fixes for 2 major issues related to network interfaces
  RHEL6_7/system/initscripts/ifcfg/preupg_network.sh
Labels: bug, needs_verify

#129 others/configchanges: fix syntax error
  RHEL6_7/others/configchanges/check
Labels: bug

#128 system/SysconfigCgroupDaemon: handle dead symlinks
  RHEL6_7/system/SysconfigCgroupDaemon/check
Labels: bug

#132 Inhibit upgrade when by-path is used in /etc/fstab
  RHEL6_7/system/fstab-bypath/check
  RHEL6_7/system/fstab-bypath/module.ini
  RHEL6_7/system/fstab-bypath/solution.txt
Labels: enhancement
